### PR TITLE
fix: choose environment to find function in for `restrict_derivation`

### PR DESCRIPTION
**Pull request by tomratford**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiraldev/devel/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [ ] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [ ] Updated relevant unit tests or have written new unit tests, which should consider realistic data scenarios and edge cases, e.g. empty datasets, errors, boundary cases etc. - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/devel/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
- [ ] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/devel/articles/programming_strategy.html#deprecation)?
- [x] Update to all relevant roxygen headers and examples, including keywords and families. Refer to the [categorization of functions](https://pharmaverse.github.io/admiraldev/devel/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [ ] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiraldev/devel/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [ ] Link the issue in the Development Section on the right hand side.
- [ ] Address all merge conflicts and resolve appropriately 
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Comment by bms63** [comment]
I like this style of commit messaging !  @pharmaverse/admiral lets revisit how we do commit messages.  I still like the issue number in the message, but I like these actions words.  On the agenda! 

image

**Comment by tomratford** [comment]
Thanks Ben. I'm roughly following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).

I've seen some repos do it like `fix(#xx): Lorem ipsum` to include the issue no. in the commit still.

**Comment by bms63** [comment]
> Thanks Ben. I'm roughly following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).
> 
> I've seen some repos do it like `fix(#xx): Lorem ipsum` to include the issue no. in the commit still.

Very cool!!  
image

**Comment by bms63** [comment]
Hey @tomratford  sorry I will review this soon.  @pharmaverse/admiral can anyone else review this as well please.

**Review by bundfussr — CHANGES_REQUESTED** [review]
I tried the reproducible example from https://github.com/pharmaverse/admiral/issues/1765 but it did not work.

**Comment by tomratford** [comment]
> I tried the reproducible example from [pharmaverse/admiral#1765](https://github.com/pharmaverse/admiral/issues/1765) but it did not work.

I know this isn't helpful but _"it works on my machine"_.

I've written [a gist to reproduce it](https://gist.github.com/tomratford/1fbe25479a51f0a70f4eea271e6ff6c7) that gives the desired output when run in my terminal. There is an [accompanying update](https://github.com/pharmaverse/admiral/blob/b39b7ecf1c1be08154046bfc39e7b26d0d834580/R/restrict_derivation.R#L84) to `admiral` that must also be installed. It updates `restrict_derivation()` so that it sends the current parent environment at the time of execution, not lazily loaded when needed in `assert_function_param()`. 
```r
...
assert_function_param(deparse(substitute(derivation)), names(args), force(parent.frame()))
...
```
I'm not sure if there's a better way to do this? It feels a little bit hacky but I couldn't get it to work any other way.

**Comment by bundfussr** [comment]
> > I tried the reproducible example from [pharmaverse/admiral#1765](https://github.com/pharmaverse/admiral/issues/1765) but it did not work.
> 
> I know this isn't helpful but _"it works on my machine"_.
> 
> I've written [a gist to reproduce it](https://gist.github.com/tomratford/1fbe25479a51f0a70f4eea271e6ff6c7) that gives the desired output when run in my terminal. There is an [accompanying update](https://github.com/pharmaverse/admiral/blob/b39b7ecf1c1be08154046bfc39e7b26d0d834580/R/restrict_derivation.R#L84) to `admiral` that must also be installed. It updates `restrict_derivation()` so that it sends the current parent environment at the time of execution, not lazily loaded when needed in `assert_function_param()`.
> 
> ```r
> ...
> assert_function_param(deparse(substitute(derivation)), names(args), force(parent.frame()))
> ...
> ```
> 
> I'm not sure if there's a better way to do this? It feels a little bit hacky but I couldn't get it to work any other way.

I would prefer a solution where the environment does not need to be specified in the `assert_function_param()` call. Maybe `arg` should not expect the function name but the function itself.

@bms63 , what do you think?

**Comment by bms63** [comment]
Sorry...just to recap.  Is a user creating a custom function in their script not able to use it in `restrict_derivation`?

**Comment by tomratford** [comment]
> Sorry...just to recap. Is a user creating a custom function in their script not able to use it in `restrict_derivation`?

Within a script, it should be fine. 

Within a [function](https://gist.github.com/tomratford/1fbe25479a51f0a70f4eea271e6ff6c7#file-ex-r-L11-L27) (or [test](https://github.com/pharmaverse/admiral/commit/59487d0f8bb043aea18a774e160f511309ef22d2)), it will break. 

My concern is that making it take function objects instead of strings is a breaking change - although I don't know how much `assert_function_param` is used across all admiral code. Could `assert_function_param` become a generic so that it could take both strings and functions?

**Comment by bundfussr** [comment]
@bms63 , see https://github.com/pharmaverse/admiral/issues/1765 for an example.

admiralophta noticed this issue.

**Comment by tomratford** [comment]
@bundfussr @bms63 

[`assert_function()`](https://pharmaverse.github.io/admiraldev/devel/reference/assert_function.html) takes a function argument and checks params. 

So maybe this PR isn't necessary and instead `assert_function()` should be used over `assert_function_param()`. Feel like I'm made a mountain out of a mole hill sorry.

**Comment by bundfussr** [comment]
@tomratford , yes, you are right. Good point!

@bms63 , I have created an issue to clean up the assertions: https://github.com/pharmaverse/admiraldev/issues/264

**Comment by bms63** [comment]
Tom I added you to repo as contributor

**Pull request closed without merging**
