### PR TITLE
Closes #358: Release dashboard

### LINKED ISSUE #358: Documentation:  Add CRAN Monitoring dashboard to release vignette
### Please select a category the issue is focused on?

_No response_

### Let us know where something needs a refresh or put your idea here!

Very helpful dashboard for monitoring progress on CRAN after uploading - should be placed in a vignette

https://r-hub.github.io/cransays/articles/dashboard.html

### PR DESCRIPTION
**Pull request by manciniedoardo**
Closes #358 

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/dev/CONTRIBUTING.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `main` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests, which should consider realistic data scenarios and edge cases, e.g. empty datasets, errors, boundary cases etc. - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#deprecation)?
- [x] Update to all relevant roxygen headers and examples, including keywords and families. Refer to the [categorization of functions](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` under the header `# admiral (development version)` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiraldev/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Comment by manciniedoardo** [comment]
@bms63 some comments:

- I added `reactable` & `cransays` to the suggests section of the `DESCRPTION` - is that enough?
- The actual code to scrape the API runs fine but with some warnings about "closing open connections" - not sure if that will be an issue or not.

**Comment by bms63** [comment]
I don't think this needs to be added to the DESCRIPTION file.  

It is just a helpful tool for monitoring the releases of the packages.  We could just build an article locally and publish it rather than building it with the package.  

Actually, I was thinking all our vignettes should just be articles and no longer ship with the package.

**Comment by manciniedoardo** [comment]
> I don't think this needs to be added to the DESCRIPTION file.
> 
> It is just a helpful tool for monitoring the releases of the packages. We could just build an article locally and publish it rather than building it with the package.
> 
> Actually, I was thinking all our vignettes should just be articles and no longer ship with the package.

If we build the article locally will it refresh periodically though?

**Comment by bms63** [comment]
> > I don't think this needs to be added to the DESCRIPTION file.
> > It is just a helpful tool for monitoring the releases of the packages. We could just build an article locally and publish it rather than building it with the package.
> > Actually, I was thinking all our vignettes should just be articles and no longer ship with the package.
> 
> If we build the article locally will it refresh periodically though?

when ever the pkgdown job runs it should rebuild the articles as well as any vignettes.  so we will have them available to us.

The R-CMD checks won't build the vignettes anymore.  this also cuts down on the size of the package

**Comment by manciniedoardo** [comment]
> > > I don't think this needs to be added to the DESCRIPTION file.
> > > It is just a helpful tool for monitoring the releases of the packages. We could just build an article locally and publish it rather than building it with the package.
> > > Actually, I was thinking all our vignettes should just be articles and no longer ship with the package.
> > 
> > 
> > If we build the article locally will it refresh periodically though?
> 
> when ever the pkgdown job runs it should rebuild the articles as well as any vignettes. so we will have them available to us.
> 
> The R-CMD checks won't build the vignettes anymore. this also cuts down on the size of the package

Sorry i'm ingnorant here - how will the articles be re-built with packages not listed anywhere?

**Comment by bms63** [comment]
maybe just an install.packages in a hidden chunk would suffice?

https://r-pkgs.org/website.html#non-vignette-articles

Why do we need to install cransays?  I thought it was just a dashboard we could view?






































































<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/bs832471/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/bs832471/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<title>Pharma R&amp;D WS – Excel Template</title>
<style>

</style>
</head>

<body link=blue vlink=purple>


13-Mar-2024
--




</body>

</html>

**Comment by manciniedoardo** [comment]
> maybe just an install.packages in a hidden chunk would suffice?
> 
> https://r-pkgs.org/website.html#non-vignette-articles
> 
> Why do we need to install cransays? I thought it was just a dashboard we could view?
> 
> <title>Pharma R&D WS – Excel Template</title> <style> </style>
> ## 13-Mar-2024
On the cransays website, the [vignette](https://r-hub.github.io/cransays/articles/dashboard.html) I used as a basis to implement this uses a cransays function to read the CRAN database.

**Comment by manciniedoardo** [comment]
Yeah, if too hard then can do that instead.

**Comment by bms63** [comment]
> Yeah, if too hard then can do that instead.

i guess i was not very clear in the issue, but I was expecting just a note on the dashboard :) Seems like this is getting hard and just making a quick note on it is good for me!!

**Pull request merged**
