### PR TITLE
Closes #71 71_comments_guide: Add Comments section to programming strategy

### LINKED ISSUE #71: Documentation:  Using Comment blocks in functions
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

It could be advantageous for developers to have commented blocks of code for future developers making updates.  These comment blocks could point out salient features of the code and/or give a more detailed explanation of how the code works/processes.  This would be seen by developers  or by users inspecting the code on github.

We would like to establish a common way to use these comment blocks in our code.  

DoD:
Programming strategy has recommended best practice for using comments blocks in code.

@sgorm123 Does this capture our discussion yesterday?

### PR DESCRIPTION
**Pull request by bundfussr**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiral/articles/unit_test_guidance.html)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiral/articles/programming_strategy.html#deprecation)?
- [x] Update to all relevant roxygen headers and examples.
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page.
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue so that it closes after successful merging.
- [x] Address all merge conflicts and resolve appropriately.
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Review by bms63 — COMMENTED** [review]
image

Sorry...not your issue, but we use styler to enforce our style convention. Do you mind sliding this into this PR.


What are your feelings about this in `admiralonco` ?  These are nice and neat, but I feel like they are just repeating the roxygen documentation and adding more lines to the file.  

image

image

**Comment by bms63** [comment]
Should we have a message that says don't do something like this 

image

**Comment by bms63** [comment]
and that our code really should be readable enough that pointing out stuff like this is not necessary.

**Comment by bms63** [comment]
ugh....looking at these more I am finding them more helpful...I feel like this was why we could never reach a decisions.  
image

**Comment by bundfussr** [comment]
I would not use the `#++++++` lines because they increase the space used for comment and distract me from the code. For me the syntax highlighting in RStudio is sufficient to distinguish code and comments.

In general I would avoid repeating information which is already provided in the header. But sometimes it is helpful to repeat requirements.

I am not sure what we should add to the guidance and how we could get to an agreement. Should we discuss it in the Wednesday meeting or ask more developers to review this PR?
@bms63 , what do you think?

**Comment by bundfussr** [comment]
I have added styler to the "Source Code Formatting" section. I have kept lintr because we use both.

**Comment by thomas-neitmann** [comment]
@pharmaverse/admiral Please review.

**Comment by DeclanHodges** [comment]
I tend to agree with not using the #++++ commenting style. I think it is better to keep it in line with the tidyverse style guide, as the comments are clear enough, but also more concise.

**Comment by bms63** [comment]
Shall we finish this one out @bundfussr?

**Comment by bundfussr** [comment]
@bms63 , yes, it would be nice to finish it.

I have added a paragraph regarding formatting of comments.

As far as I remember we did not have a final decision. Thus I have added it to the agenda for next Wednesday.

By the way, why is version 0.2.1 in `devel` but not in `main`?

**Comment by bms63** [comment]
> @bms63 , yes, it would be nice to finish it.
> 
> I have added a paragraph regarding formatting of comments.
> 
> As far as I remember we did not have a final decision. Thus I have added it to the agenda for next Wednesday.
> 
> By the way, why is version 0.2.1 in `devel` but not in `main`?

I approved a PR that had the version at `0.2.1` and it should be `0.3.0`.  Can you update here for us? https://github.com/pharmaverse/admiraldev/pull/198/files

**Comment by bundfussr** [comment]
@bms63 , I see. I have updated NEWS.md.

**Comment by bundfussr** [comment]
@bms63 , I fixed the checks. They just failed due to a issue on github side. So rerunning them was enough.

Could you approve?

**Review by bms63 — APPROVED** [review]
Yay!!! Comments!!

**Pull request merged**
