### PR TITLE
copied code from admiral #1257

### LINKED ISSUE #1: Automate adding function name and test number to the test title
A function should be implemented which adds the function name and a test number to the title of the tests. Additionally it should add a comment before the test such that it is displayed in the TOC in RStudio.
For example
```
test_that("duration and unit variable are added", {
...
}
```
should be transformed to
```
#---- derive_vars_aage, test 1: duration and unit variable are added ----
test_that("derive_vars_aage, test 1: duration and unit variable are added", {
...
}
```
If the function name and test number are already in the title, it should be updated if necessary.

Please note this is quite a large task and good for someone familiar with the RStudio API.

### PR DESCRIPTION
**Pull request by slamao**
Copied from https://github.com/pharmaverse/admiral/pull/1257
Closes #1 

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/main/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiral/main/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiral/main/articles/programming_strategy.html#deprecation-1)?
- [x] Update to all relevant roxygen headers and examples.
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [ ] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/main/reference/index.html)" page.
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue so that it closes after successful merging.
- [x] Address all merge conflicts and resolve appropriately.
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Comment by slamao** [comment]
@bms63 there are some discrepancies in the package - is the package called admiraldev or admiralext? I can see both names within the package

**Comment by bms63** [comment]
It is called `admiraldev`

**Comment by slamao** [comment]
There are some errors regarding URL checks that are not related to my code change. I am not sure how you would prefer to fix this (they refer to codecov badge, PR templates etc), could you please have a look at that?

**Comment by bms63** [comment]
Hey @slamao  no worries on the urls.  I just got this going yesterday so still some kinks to work out.

Could you change `main` to `devel` in the PR please?  then we will be good to go.

**Comment by slamao** [comment]
Ok thanks, sounds good. Changed target to devel.

**Comment by slamao** [comment]
Thanks for merging and glad to hear that it is working. Hope it will help you all. Cheers!

**Pull request merged**
