### PR TITLE
Closes #106 106_add_suffix_to_vars: implement add_suffix_to_vars()

### LINKED ISSUE #106: Feature Request: Implement `add_suffix_to_vars()`
### Feature Idea

Implement `add_suffix_to_vars()`. This is required for https://github.com/pharmaverse/admiral/issues/1448.

### Relevant Input

_No response_

### Relevant Output

_No response_

### Reproducible Example/Pseudo Code

_No response_

### PR DESCRIPTION
**Pull request by bundfussr**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiral/articles/unit_test_guidance.html)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiral/articles/programming_strategy.html#deprecation)?
- [x] Update to all relevant roxygen headers and examples.
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page.
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue so that it closes after successful merging.
- [x] Address all merge conflicts and resolve appropriately.
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Review by bms63 — COMMENTED** [review]
Should we move these to the `quo.R` file since they are using the `quo` family and keywords.

**Comment by bundfussr** [comment]
@bms63 , should we move `replace_values_by_names()` as well (and change the keyword to "quo")?

**Comment by bms63** [comment]
I think it has the `quo` keyword already which is why I thought of it, but yes I think they should both go in there.  I don't want to make more work, but what do you think about them starting with `quo_` just so they are easier to find for developers?

`replace_symbol_in_quo > quo_replace_symbol`
`add_suffix_to_vars > quo_add_suffix`

Long term, I want to get rid of the `dev_utilities.R` file and have common naming conventions for all our developer functions...maybe a little ambitious.

**Comment by bundfussr** [comment]
I think we should not add keywords like "quo" to function names because it requires a lot of code changes. For example if we rename `replace_values_by_names()` to `quo_replace_values_by_names()`, we would need to update all calls of the function in admiral core and every admiral extension package. Furthermore, we could not regroup the functions in the future.

**Comment by bundfussr** [comment]
@bms63 , I have moved the new functions and `replace_values_by_names()` to `quo.R`.

**Comment by bundfussr** [comment]
I do not know why the 3.6 check is failing. Locally it passes. As we want to get rid of 3.6 anyway, I would ignore it.

@bms63 , @thomas-neitmann , do you agree?

**Comment by bms63** [comment]
I'm hesitant to let it slide.  I will take a look.  This has happened to me in the past with 3.6 and tests being slightly different and failing.

image

**Comment by bms63** [comment]
Sorry @bundfussr no luck.  @thomas-neitmann what do you think?

I looked at these two links as they seemed slightly similar.

https://github.com/tidymodels/recipes/issues/479
https://stackoverflow.com/questions/56218641/testing-equality-of-tibbles-with-list-columns-or-nested-data-frame

**Comment by thomas-neitmann** [comment]
> I do not know why the 3.6 check is failing. Locally it passes. As we want to get rid of 3.6 anyway, I would ignore it.

I agree with this sentiment. It's time to get rid of the 3.6 checks. It's not worth our time bothering about it.

**Pull request merged**
