### PR TITLE
Closes #446: Adding `lifecycle_verbosity` to tests of deprecated functions

### LINKED ISSUE #446: Add lifecycle option `lifecycle_verbosity = 'quiet'` to tests of deprecated functions
This will silence the lifecycle warnings in the unit tests for the deprecated functions. 

```r
test_that("feature still works", {
  withr::local_options(lifecycle_verbosity = "quiet")
  expect_true(my_deprecated_function())
})
```

### PR DESCRIPTION
**Pull request by ddsjoberg**
Deprecated functions, by design, throw warnings about those deprecations. Adding `withr::local_options(lifecycle_verbosity = "quiet")` inside the unit testing chunks for the tests we've written for these functions will quiet the lifecycle warnings.

---

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/dev/CONTRIBUTING.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `main` branch until you have checked off each task.

- [x] Place Closes #446 into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests, which should consider realistic data scenarios and edge cases, e.g. empty datasets, errors, boundary cases etc. - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#deprecation)?
- [x] Update to all relevant roxygen headers and examples, including keywords and families. Refer to the [categorization of functions](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` under the header `# admiral (development version)` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiraldev/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Review by bms63 — APPROVED** [review]
Should we also have this practice in admiral?

**Comment by bms63** [comment]
> > Should we also have this practice in admiral?
> 
> If we want to have it, we should update the "Deprecation" section in the Programming Strategy.

okay there is also this use of deprecate_soft that is nice as well.  I will make an issue

**Comment by ddsjoberg** [comment]
> > Should we also have this practice in admiral?
> 
> If we want to have it, we should update the "Deprecation" section in the Programming Strategy.

@bms63 @bundfussr I think either this solution or removing tests for deprecated functions work for us. we just dont want to gunk up the testing output with warnings about deprecated functions that are entirely expected

**Comment by bundfussr** [comment]
> > > Should we also have this practice in admiral?
> > 
> > 
> > If we want to have it, we should update the "Deprecation" section in the Programming Strategy.
> 
> @bms63 @bundfussr I think either this solution or removing tests for deprecated functions work for us. we just dont want to gunk up the testing output with warnings about deprecated functions that are entirely expected

I would not remove the tests for deprecated functions because we should ensure that they still work as expected. Currently we use `suppress_warning()` to suppress the deprecation warnings. I think it doesn't matter whether we use `suppress_warning()` or `withr::local_options(lifecycle_verbosity = "quiet")`.

**Comment by bms63** [comment]
> > > > Should we also have this practice in admiral?
> > > 
> > > 
> > > If we want to have it, we should update the "Deprecation" section in the Programming Strategy.
> > 
> > 
> > @bms63 @bundfussr I think either this solution or removing tests for deprecated functions work for us. we just dont want to gunk up the testing output with warnings about deprecated functions that are entirely expected
> 
> I would not remove the tests for deprecated functions because we should ensure that they still work as expected. Currently we use `suppress_warning()` to suppress the deprecation warnings. I think it doesn't matter whether we use `suppress_warning()` or `withr::local_options(lifecycle_verbosity = "quiet")`.

Not sure of all the inner workings, but suppress_warnings() is an admiral custom function that puts the kibosh on any warnings wherease the lifecycle one is just specific to the lifecycle warnings??  If so, I sort of lean towards using the lifecycle one going forward and saving the suppress_warning() for the big guns.

**Pull request merged**
