### PR TITLE
Removed the `quosure` argument from `vars2chr()`, `get_source_vars()`…

### PR DESCRIPTION
**Pull request by ProfessorP-beep**
…, and `replace_values_by_names()` functions. Reran the test scripts and did search for other uses of the argument.

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/dev/CONTRIBUTING.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `main` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests, which should consider realistic data scenarios and edge cases, e.g. empty datasets, errors, boundary cases etc. - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#deprecation)?
- [x] Update to all relevant roxygen headers and examples, including keywords and families. Refer to the [categorization of functions](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` under the header `# admiral (development version)` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiraldev/reference/index.html)" page. 
- [ ] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [ ] Link the issue in the Development Section on the right hand side.
- [ ] Address all merge conflicts and resolve appropriately
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Review by bms63 — COMMENTED** [review]
Can you remove the .vscode - we can add that to the .gitignore if needed.

Were these functions removed in previous release.  Unsure if we need to follow the deprecation process? https://pharmaverse.github.io/admiraldev/dev/articles/programming_strategy.html?q=depreca#deprecation

**Comment by bms63** [comment]
and thanks for working on this!!

**Comment by ProfessorP-beep** [comment]
@bms63 No worries! Yea, I'll delete it and from what I saw it looked like deprecation was on phase 2 with the warning and deprecation messages already, unless I understood the doc wrong, so just removed the argument.

**Comment by bms63** [comment]
> @bms63 No worries! Yea, I'll delete it and from what I saw it looked like deprecation was on phase 2 with the warning and deprecation messages already, unless I understood the doc wrong, so just removed the argument.

awesome!!  Thanks!

**Comment by ProfessorP-beep** [comment]
Hey my Power supply on my desktop conked out during a storm. I got a replacement on the way and can hop on and fix the issues in about a week. 

I can also just steal my wife's laptop in the off hours in the meantime as well and get a setup going haha.

**Comment by bms63** [comment]
oh bummer sorry to hear about that!!  I do everything on [posit.com - ](https://posit.cloud/) if having an IDE/R is holding you up!

**Pull request closed without merging**
